Repository felikatze/isat-script-project, pull requests merged in 2024-10, with the labels that each got.

#163 dormont change god statue
  public/random/deaths.html
  public/rooms/dormont/changegod.html
  public/rooms/dormont/meadow.html
  public/styletest.css
Labels: script page

#171 sasasap expressions :>
  public/acts/act2/ending2.html
  public/acts/act3-4/intro3.html
  public/acts/act3-4/kingquest.html
  public/acts/act3-4/loopquest.html
  public/acts/act5/VSFriends.html
  public/acts/act6/isaend6.html
  public/bars.js
  public/events/ghost.html
  public/events/odilesus.html
  public/rooms/dormont/dormdile.html
  public/rooms/dormont/favortree.html
  public/rooms/dormont/isatalk.html
  public/rooms/end/endrooms.html
  public/rooms/end/odileend.html
  public/rooms/floor1/snackbreak1.html
  public/rooms/floor2/secret_library.html
  public/rooms/floor2/snackbreak2.html
  public/rooms/floor3/changeroom.html
  public/rooms/king/kingfight.html
  public/rooms/loop/whattodoact34.html
  public/sasasap/deathssap.html
  public/sasasap/kingfightsap.html
  public/sasasap/lastroom.html
  public/sasasap/perfend.html
  public/sasasap/trueend.html
  public/styletest.css
Labels: enhancement

#172 expressions fixes + implemented exceptions
  public/bars.js
  public/rooms/dormont/favortree.html
  public/rooms/loop/loopfight.html
  public/sasasap/hallwayssap.html
  public/sasasap/kingfightsap.html
  public/sasasap/lastroom.html
Labels: enhancement

#177 loop chats + generic reformatted!!
  public/random/dagger.html
  public/random/generic.html
  public/rooms/loop/chats.html
Labels: enhancement

#189 inline note fix
  public/rooms/dormont/isatalk.html
  public/styletest.css
Labels: bug
