Repository felikatze/isat-script-project, pull requests merged in 2024-08, with the labels that each got.

#94 act 5 king fight
  public/feed.xml
  public/index.html
  public/overview/acts.html
  public/overview/rooms.html
  public/rooms/king/kingfight-act5.html
  public/rooms/king/kingfight.html
  public/styletest.css
Labels: script page, requests

#96 mal du pays reformat + screenreader css
  public/acts/act5/maldupays.html
  public/feed.xml
  public/styletest.css
Labels: enhancement

#122 changed order of navbar
  public/bars.js
Labels: enhancement

#95 all snack break pages reformatted + act 5 friendquests reformatted + BONNIEQUEST!
  public/acts/act3-4/bonniequest.html
  public/acts/act3-4/isaquest.html
  public/acts/act3-4/miraquest.html
  public/acts/act3-4/odilequest.html
  public/acts/act5/friendquestsACT5.html
  public/feed.xml
  public/index.html
  public/overview/acts.html
  public/portraits.html
  public/rooms/dormont/isatalk.html
  public/rooms/floor1/snackbreak1.html
  public/rooms/floor2/snackbreak2.html
  public/rooms/floor3/mirrorroom.html
  public/rooms/floor3/snackbreak3.html
  public/rooms/loop/whattodoact34.html
  public/styletest.css
Labels: enhancement, requests

#126 vsfriends reformatting
  public/acts/act5/VSFriends.html
  public/feed.xml
  public/styletest.css
Labels: enhancement
